embed_dir: "/mnt/share/data/EMBED"
rsna_dir: "/mnt/share/data/RSNA-Pheumonia"
model_name: "resnet"
model_n_layer: 5
model_n_iter: 8
img_size: 512
batch_size: 12
learning_rate: 0.0001
min_lr_ratio: 1
max_epoch: 1000
patience: 25
num_worker: 24