#dataset_dir: "/mnt/share/data/EMBED"
dataset_dir: "/mnt/share/data/RSNA-Pheumonia"
model_name: "resnet"
img_size: 512
batch_size: 24
learning_rate: 0.0001
min_lr_ratio: 1
max_epoch: 1000
patience: 50
num_worker: 24
bpf_res: 0.05